# Generated by Django 2.2.6 on 2019-11-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('ph11', 'Physics 11'), ('ph12', 'Physics 12')], default='ph11', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Lobjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectvie_code', models.CharField(max_length=8)),
                ('objective_description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=12)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('objectives', models.ManyToManyField(to='questions.Lobjective')),
            ],
        ),
    ]
