# Generated by Django 2.2.6 on 2019-11-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('ph11', 'Physics 11'), ('ph12', 'Physics 12')], max_length=20),
        ),
    ]
