# Generated by Django 2.2.6 on 2019-11-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191103_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobjective',
            name='objective_description',
            field=models.CharField(max_length=200),
        ),
    ]
