# Generated by Django 2.2.6 on 2019-11-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191103_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobjective',
            name='objective_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
