# Generated by Django 2.2.6 on 2019-11-06 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20191103_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(blank=True, max_length=255)),
                ('question_text', models.TextField()),
                ('answer', models.CharField(max_length=40)),
                ('document', models.FileField(upload_to='documents/')),
                ('lobjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Lobjective')),
            ],
        ),
    ]
