# Generated by Django 2.2.7 on 2019-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20191105_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload_img',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
