# Generated by Django 2.2.7 on 2019-11-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_practice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
