# Generated by Django 2.2.7 on 2019-11-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_delete_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('questions', models.ManyToManyField(to='questions.Question')),
            ],
        ),
    ]
